name: test

on: push

jobs:
  linting:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.3.0

      - uses: bahmutov/npm-install@v1

      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          MODE: local
          NODE_OPTIONS: '--max_old_space_size=4096'
          LOG_LEVEL: warn
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
          DATABASE_NAME: 'test'
          TEST_DATABASE_NAME: 'test'
          DATABASE_USER: 'test'
          DATABASE_PASSWORD: 'test'

      - name: Run DB Migration
        run: npm run typeorm -- migration:run

      - name : Run e2e test
        run: npm run test:e2e